name: Generate Semantic Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release